# Generated by Django 4.1.5 on 2023-01-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_vadich_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='vadich',
        ),
    ]
